apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
        - name: bid-svc
          image: dorume/bid-svc
          imagePullPolicy: Never
          env:
            - name: RabbitMq__Host
              value: rabbitmq-clusterip
            - name: RabbitMq__Username
              value: rabbitmq
            - name: RabbitMq__Password
              value: rabbitmq
            - name: ConnectionStrings__BidDbConnection
              value: mongodb://root:mongopw@mongo-clusterip
            - name: IdentityServiceUrl
              value: https://id.dorume.online
            - name: GrpcAuction
              value: http://auction-clusterip:7777
---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-svc
  ports:
    - port: 80
      targetPort: 80
      name: web
