apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
        - name: gateway-svc
          image: dorume/gateway-svc
          imagePullPolicy: Always
          env:
            - name: ClientApp
              value: https://app.carsties.com
            - name: IdentityServiceUrl
              value: https://id.dorume.online
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
    - port: 80
      targetPort: 80
